= ANF devlog #2: Object-oriented rendering API
:revdate: Sep 4, 2020

== Devlog

自前の 2D フレームワークが実用に近づいてきました。

前回、 https://github.com/toyboot4e/rust-fna3d[FNA3D] でイカちゃんを表示した所からの続きです。

=== Rendering pipeline overview

https://learnopengl.com/[learnopengl.com] の第一章を読み、知識が補填されました。 Texture sampling, mipmap, vertex/fragment shader, uniform などなど……。 OpenGL は古すぎる API のように言われていますが、他の API との共通部分も多いようなので、このサイトもタメになると思います。

Graphics card (GPU が詰まったハード) 側の処理を図示してみました。これは _rendering pipeline_ と呼ばれます:

.Rendering pipeline (I guess. *may be incorrect*)
[ditaa,"anf/pipeline"]
----
---|              +------------------------------------------------------------------------------------+
   |              | (required)                                    (required)                           |
   |              | +--------+            +----------+            +----------+            +----------+ |
   | vertices     | | vertex |  vertices  | geometry | primitives | fragment | fragments  | alpha    | |  pixels
   | -----------> | | shader | ---------> | shader   | ---------> | shader   | ---------> | blending | |  ------->
   | (draw call)  | +--------*            +----------+            +----------+            +----------+ |  draw
   |              |    maps                 reshapes                 paints                 blends     |
---|              +------------------------------------------------------------------------------------+
CPU                                                 Graphics card
----

* GPU が効率的に使えるメモリがあり、 GPU が使用するデータ (頂点データや texture) はそこに入れます。 CPU 側は、 GPU メモリ側へのデータの _upload_ (send/copy) 後は、 CPU 側のメモリを開放しても構いません。普通は開放します。
* _Draw call_ とは、 `glDraw**` みたいな `draw` 関数の呼び出し (drawing funtion call) です。これらの関数は、 graphics card 側へ頂点データを送り、 _rendering pipeline_ を _kick_ します (動かします) 。
* Rendering pipeline では 3D データを 2D 画面に投影します。 2D ゲームでは orthographics projection matrix を使うのが一般的で、深さ軸 (z 軸) を使わないと思います。 Depth/stencil buffer とかでは使うかもしれません。
* 注意: この図には rasterizing/clipping などが抜けています。どこに入るんでしょう……。

まだまだですが、意外と理解できそうです。 2D だから簡単というのもあります。

=== Refactoring

https://github.com/floooh/sokol/blob/master/sokol_gfx.h[sokol_gfx] が分かりやすそうです。非常によくコメントされており、多数のデータを束ねる型もあります (`sg_bindings`, `sg_pipeline`) footnote:[Sokol で分かりにくそうなのは、 `#ifdef` を使っている部分です。 `#ifdef` を読み飛ばすと、かなり分かりやすく見えました] 。一方、 FNA3D は不親切で、中々把握できません。

そこで、 *インクリメンタルな開発* に振り切ることにしました。僕が知らない機能、僕が使わない機能は実装せず、 https://www.google.com/search?q=WIP[WIP] のコードもありません。『見れば分かる』コードになったと思います。

以下のような切り捨てをしました:

* 色々諦めて *単ウィンドウ・シングルスレッドにする* 。
* 今後の拡張性を考えたコードは削除する。たとえば、 _mipmap_ を使わないので `mipmap` フィールドを削除しました。
* あまり抽象化せず、具体的な型やフィールドを直接使う。

意外と気持ちの割合が大きいですね。気持ちの上での『切り捨て』は、つまり優先度の設定と同じだと思います。分かっていることだけでコードを組んで、必要になったら新しい知識を仕入れるようにしました。

コードの修正には `cargo +nightly doc` で生成される *ドキュメントページを基準に* しました。ドキュメントが分かりやすければ、コードも分かりやすいはずです。


リファクタリングには時間が必要でしたが、他のどの 2D フレームワークよりも分かりやすくなったと思います。コードは 2,000 行弱。もちろん、機能不足のためですが……。

=== Rendering API

画像の表示は以下のようにします:

[source,rust]
----
use anf::gfx::{DrawContext, Texture2D};

fn example_rendering(dcx: &mut DrawContext, tex: Texture2D) {
    let mut pass = dcx.pass(); // RenderPass
    pass.texture(tex).dest_pos_px(100.0, 100.0);
    pass.texture(tex).dest_pos_px(100.0, 400.0);
}
----

* `DrawContext`: `RenderPass` を発行できるオブジェクトです。
* `RenderPass` footnote:[この _render pass_ が元の用語と正しく対応しているのかは分かりません。]: ある状態セットに対して `SpritePushCommand` を発行できるオブジェクトです。たとえば、ある `RenderTarget` への書き込みは、 1 つの `RenderPass` を経由して行います (予定) 。

== Repositories

今後は人の Rust 製フレームワークを参考にしたいと思います。

* https://bevyengine.org/[Bevy Engine]
+
今年 8 月に出たゲームエンジンです。 https://bevyengine.org/news/introducing-bevy/[Introducing Bevy] を見て、 *この世で最も綺麗な API* を持つゲームエンジンなんじゃないかと思いました。動的な機能を非常に上手く使っています。特にアセット管理 (`Assets`, `AssetLoader`) とグローバルオブジェクトの管理 (`Resource`, `Resources`, `Res<T>`, `ResMut<T>`) を参考にしようと思います。

* https://tetra.seventeencups.net/[tetra] (https://docs.rs/tetra/latest/tetra/[API])
+
XNA に影響を受けたという 2D フレームワークです。 `time` モジュールのコメント量が多かったので、ゲームループを作るときに参考にします。 https://docs.rs/ggez/latest/ggez/[ggez] と同様に、 `Context` にグローバルな依存性を置いています。このパタンについては、今後の記事で触れようと思います。

* https://github.com/not-fl3/miniquad[miniquad] (https://docs.rs/miniquad/latest/miniquad/[API])
+
Sokol に影響を受けたという 2D rendering library です。やはり FNA3D には無いような大きな単位の構造体が提供されているので、参考にするかもしれません。

* https://github.com/gfx-rs/wgpu-rs[wgpu-rs] (https://docs.rs/wgpu/latest/wgpu/[API])
+
https://wgpu.rs/[Web GPU] (wgpu) もやはり参考になりそうです。 https://docs.rs/wgpu/latest/wgpu/struct.RenderPass.html[RenderPass] や `*Descripter` を使った API は、 FNA3D は OpenGL とはかなり異なっているようです。

* https://github.com/not-fl3/macroquad[macroquad] (https://docs.rs/macroquad/latest/macroquad/[API])
+
https://github.com/raysan5/raylib[raylib] に影響されたという 2D rendering library です。すべてのアイテムをフラットに公開しているのが特徴的です。内部的には、なんと global state (static 変数) を活用しています。また、 _lifetime_ など Rust 特有の機能を隠しています。僕がやらない方向性なので参考になります。所々で知性を感じるのもいい感じです。

* https://github.com/hecrj/coffee[coffee] (https://docs.rs/coffee/latest/coffee/[API])
+
GUI が凄そうな 2D フレームワークです。

docs.rs の読みさすさのおかげで、人の設計に簡単に触れることができます。やはり Rust は環境が素晴らしい！

== Wrapping up

ANF の `DrawContext` は builder 風の API で、他のフレームワークと比べても意外と良い出来になりそうです。

目下の悩みは、 FNA3D の自動ビルドと、出力への同封です。 https://github.com/alexcrichton/cmake-rs[cmake-rs] でささっと行けるかと思ったのですが、苦戦しています。

