= Lang #2: Crafting Interpreters - 2/2
:book: https://craftinginterpreters.com/contents.html[Crafting Interpreters]

== Devlog

{book} の Part III (A Bytecode Virtual Machine) を Rust でやってみました。入力を入れると出力が帰ってくるプログラミングは癒されます。デバッグが楽ですね。ゲームの方が大変だと思います。

元の本では C 言語を使っており、 Rust を使ったのは若干チート気味かもしれません。何せ、 Rust には `enum` や `std::collections` があります。データ構造を実装する章は、大体飛ばしてしまいました。

=== Lexer (scanner, tokenizer)

ソースコードを `Token` へ分解するのは、 `Scanner` か `Lexer` でしょう。Tokenizer と言うと、単純に単語分解するようなニュアンスがあるようです。

大雑把にこんな形になりました。元の本からは、やや離れたやり方です:

.lex.rs
[source,rust]
----
/// [lo, hi) in bytes
pub struct Span { // <1>
    lo: usize,
    hi: usize,
}

pub enum Token {
    /// Whitespace, i.e. invisible characters: ` `, `\t`, `\r` and `\n`
    Ws, // <2>
    // ~
}

/// Spanned token in source code
pub struct SpanToken {
    sp: Span,
    tk: Token,
}

/// Slices given string into loss-less spans; even whitespaces are not lost!
pub fn lex<'a>(src: &'a str) -> impl Iterator<SpanToken>; // <3>
----
<1> ソース文字列を `Token` でタグ付けされた `Span` (`SpanToken`) に分けるのが目標です。
<2> 空白も `SpanToken` として記録します。 `lex` 後のロスはありません。
<3> `lex` は context-free です。たとえば、 `&&` (and and) 演算子と `&&` (二重参照) を区別せず、どちらも `&` 2 つと見做します。後のステップで、 Parser が、どちらを選択すべきか文脈に応じて考えます。

文字列は、開始から終了まで 1 つの `Token` として表すことにしました。たとえば、 `"string"` が 1 つの `Token` です。後で `string` という中身を取り出すためには、 `"` を取り除く処理が必要です。

`Span` を使うと、ソースコード上の位置の情報を完全に保持できるため、エラーレポートや LSP の実装が簡単になりそうです。

`lex` が上手く動作しているか確認するため、ソースコードを着色して返すプログラムを作りました:

