= SSG #2: Rust + Asciidoctor
:revdate: Apr 17, 2020

ブログ生成を bash から Rust に移行しました。

* https://github.com/toyboot4e/devlog[repository] / https://github.com/toyboot4e/devlog/tree/master/ssg_rs[ssg_rs]

html を木にパースしてから加工しています。 https://handlebarsjs.com/[Handlebars] の使い方を調べるか、 `.adoc` ファイルをテンプレート代わりに使う方向性の方が良かったかもしれません。

NOTE: 追記: 今回作った ssg_rs が良くなかったため、マークアップ言語 + SSG の作成を link:/posts/9_booktune_1.html[始めました]。

== Background

link:/posts/3_blog.html[前回]、 bash を使ってブログを生成しました。十分に機能しましたが、機能追加には厳しいものがありました。したがって、今回はプログラミング言語を使い、柔軟性を高めました。

== impl ssg_rs

=== Environment

https://rvm.io/[rvm] を使って https://asciidoctor.org/[Asciidoctor] を再インストールすると、原稿の変換速度が *3 倍以上* に改善されました。Mac の Homebrew/rbenv 経由だと、間のスクリプトが遅かったのではないかと思います。 `rbenv` を使っている人は、 https://asciidoctor.org/docs/install-asciidoctor-macos/[検討] されてみてはいかがでしょうか。

また、 Rust では https://github.com/rust-analyzer/rust-analyzer[rust-analyzer] が rls の代替となるようなので、移行しました。

=== Parsing

html を文字列ベースで (タグ名を `enum` にせずに) パースしてみました。また、 html の builder を作りました。しかし、結局必要だったのは templating engine に相当する機能だと分かりました。 [line-through]#つまり無駄でした# *このブログ専用のジェネレータとなってしまいました*。

=== How to use

`ssg_rs` は、以下のようなファイル構成を前提とします:

.Directory layout for ssg_rs
[source,sh]
----
.
├── img/
├── posts/
├── drafts/
├── site/
├── ssg/
└── styles/
----

`ssg/` 以下に、 https://github.com/ron-rs/ron[Rusty Object Notation] で書いた設定ファイルを置きます:

.ssg/setup.ron
[source,dart]
----
Config(
    layout: Layout(
        markups: ["posts", "read"],
        dest: "site",
        img: "img",
        styles: "styles",
    ),
    site: Site(
        title: "Toy toy beam",
        message: "toyboot4e のブログです。プライベートな気分で記事を書きます。",
    )
)
----

`struct` の上に `#derive[Deserialize]` と書くだけで、設定ファイルから `deserialize` できるようになります。

=== Rust!

CLI 引数は https://github.com/clap-rs/clap[clap] (ver. 3) でパースしました。また、標準ライブラリがしっかりと活躍しました。 *エラーが大量に出る* のが Rust の特徴だと感じましたが、かえって *インクリメンタルに* 変更に強いコードへリファクタリングする必要が出て良かったです。

エラーが出る度に、共通箇所をまとめました。その結果、高階関数が非常によく活躍しました。共通の引数が多い場合は、 `struct` にキャプチャすべき変数をまとめ、関数はメソッドになりました。

== Wrapping up

bash (400 行弱) から Rust (2,000 行強) へ移行しました。この程度の複雑さには、コンスタントに対処できそうです。成果としては、オプションを指定することで、下書きファイル (`drafts/*`) も変換できるようになりました。

今後は、 *より多彩なサイト生成が可能な SSG* を目指してみようと思います。設計的に面白そうですし、 https://asciidoctor.org/[Asciidoctor] に native 対応した SSG は少ないこともあり、若干のモチベーションがあります。差し当たり、 https://github.com/rust-lang/mdBook[mdbook] の代替として、 `adbook` を作ることを目標に考えています。

=> 追記: マークアップ言語と SSG の両方を自作する方向に舵を切りました。マークアップ言語にテンプレート言語を兼ねさせてみたいです。

