= Batcher
:revdate: Dec 17, 2020
:cpp: pass:[C++]
:macruqoad: https://github.com/not-fl3/macroquad[macroquad]
:miniquad: https://github.com/not-fl3/miniquad[miniquad]
:quad-snd: https://github.com/not-fl3/quad-snd[quad-snd]

== Devlog

使用ライブラリを {fna3d} ({rust-fna3d}) + SDL から {sokol} ({rokol}) に移行しました。全面的に作り直しです。

NOTE: 以前の開発は、サイドバーの ANF devlog に載っています。

=== Motivation

{Sokol} の方が学習に有利だと思いました:

[cols="1,4"]
|===
| 2D       | {zig-gk} は Sokol 似の {zig-rk} の上に作られています。
| 3D       | {learn-gl-sokol} があります。
| シェーダ | Gaussian blur をやりたいものの、 FNA3D の方はシェーダが全然分かりません。
|===

2D 開発では {zig-gk} を真似ます。

=== 2D rendering

今回書き直したのは `Batcher` です。画像表示ができるようになりました。

==== Rendering objects in Rokol

{rokol} (Sokol の wrapper) の使用例です:

[source,rust]
----
use rokol::{app as rg, gfx as rg};

struct AppData {
    /// 描画 (rendering pass) 開始時のクリア色を指定するデータ
    pa: rg::PassAction,
    /// Shader, render states (rasterizer, blend, sampler) and vertex/index information
    pip: rg::Pipeline, // <1>
    /// Index buffer, vertex buffers and image slots
    bind: rg::Bindings, // <2>
}
----
<1> `Pipeline` は基本的に *シェーダ* のことだと言えそうです。
<2> `Bindings` は *描画対象* のデータです。これに `draw` 関数を生やしたら `Mesh` と言えるようです。 2D 画面は dynamic mesh です。

==== Rendering API in Rokol

以下のように描画します:

[source,rust]
----
impl AppData {
    fn render(&mut self) {
        {
            // スクリーンへの描画パスを開始 (`PassAction` でクリア色を指定)
            rg::begin_default_pass(&self.pa, ra::width(), ra::height());

            // Pipeline (シェーダ、 render states と vertex/index attributes) をセット
            rg::apply_pipeline(self.pip);
        } // <1>

        {
            // index buffer, vertex buffers と image slots をバインド
            rg::apply_bindings(&self.bind);

            // バインドしたバッファの一部を描画 (base_elem, n_indices, n_instances)
            rg::draw(0, 6, 1);
        } // <2>

        // 描画パスを終了
        rg::end_pass();

        // フレームバッファの入れ替え
        rg::commit();
    }
}
----

この API を 2D に特化して見直すと、さらに洗練可能です:

<1> 2D ではシェーダと vertex/index buffer が既知だとします。 `begin_pass` の中で `apply_pipeline` ができるので、 1 つの関数にまとまります: `begin_pass(PassConfig { PassAction, Shader, RenderStates, Option<RenderTexture> })` 。
<2> `Batcher` が描画します。ユーザから見れば、送った sprite が自動的に描画されます。

==== snow2d

最終的な 2D の API を `snow2d` というクレートにして、

[source,rust]
----
fn render(&mut self) {
    // フレームバッファへの rendering pass 兼 draw call の batcher を開始
    let mut batch = snow2d::begin_pass(PassConfig::default());
    batch.sprite(&self.sprite)
         .dst_pos([100.0, 100.0])
         .rot(3.14 / 3.0); // <1>
    drop(batch);

    // Offscreen rendering を開始 <2>
    let mut batch = snow2d::begin_pass(PassConfig {
        target: Some(&mut self.offscreen_target),
        ..Default::default()
    });
    // ~~
}
----
<1> 描画用 API は builder 風です。
<2> Offscreen rendering (texture への rendering) (予定)

=== Wrapping up

Sokol の API が綺麗で綺麗で……。基本的に、シェーダと描画対象 (`Bindings` あるいは `Mesh`) しか存在しないのですね。今のところ、そんな認識でいます。

