= Books about command line
:revdate: Nov 11, 2019

== Books

Shell, Vim, Git に関する本をリストしました。

===  新しい Linux の教科書

[cols="1,3"]
|====
| 書名     | https://www.amazon.co.jp/%E6%96%B0%E3%81%97%E3%81%84Linux%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8-%E4%B8%89%E5%AE%85-%E8%8B%B1%E6%98%8E/dp/4797380942/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=[新しいLinuxの教科書]

| 著者     | 三宅 英明、大角 祐
| 出版日   | 2015/06/06
| ページ数 | 440
|====

Linux = Unix シェル (bash) とした入門書です。相対パスや絶対パス、環境変数など、 *基礎知識のバックアップ* を丁寧にやってくれる本でした。

内容は、ネット検索で手に入るものと言えますが、一冊の本として仕上げられており、ネットの断片的な情報よりも遥かに贅沢です。コラムも面白く、著者の心遣いを満喫できます。

初期投資に良い本でした。投資がスカになるのでは、という懸念はよくありますが、この本は違いました。

=== シェルプログラミング実用テクニック

[cols="1,3"]
|====
| 書名     | https://www.amazon.co.jp/%E3%82%B7%E3%82%A7%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E5%AE%9F%E7%94%A8%E3%83%86%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF-Software-Design-plus-%E4%B8%8A%E7%94%B0/dp/4774173444/ref=tmm_other_meta_binding_swatch_0?_encoding=UTF8&qid=&sr=[シェルプログラミング実用テクニック]

| 著者     | 上田隆一
| 出版日   | 2015/05/15
| ページ数 | 416
|====

``sed``, ``grep``, ``awk`` など、いわゆる _Unix filter_ で _one-liner program_ を書き、様々な作業を行います。この本のおかげで、僕はシェルを常用するようになりました。

文字列処理さえできれば、シェルは 8 割方マスターできたと言って良さそうです。その観点では、二章までが基本、三〜八章は応用となります。基本の中にエッセンスのクリームを漏れ出んばかりに押し込んでくれているので、応用部分は消化試合のように思いました。

濃い内容に、丁寧な説明が着いています。文章量が多く、初見では噛み砕くのが難しかったです。文章すべてがしっくりと来て、うんうんそうだね……と言えるようになったとき、本の真価が分かります。

読後は、胸を張って言って良いと思います。 https://enpedia.rxy.jp/wiki/チョットデキル[コマンドライン チョットデキル] 。……言い過ぎました。

=== フルスクラッチから1日でCMSを作る シェルスクリプト高速開発手法入門 改訂2版

[cols="1,3"]
|====
| 書名     | https://www.amazon.co.jp/%E3%83%95%E3%83%AB%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%83%E3%83%81%E3%81%8B%E3%82%891%E6%97%A5%E3%81%A7CMS%E3%82%92%E4%BD%9C%E3%82%8B-%E3%82%B7%E3%82%A7%E3%83%AB%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E9%AB%98%E9%80%9F%E9%96%8B%E7%99%BA%E6%89%8B%E6%B3%95%E5%85%A5%E9%96%80-%E6%94%B9%E8%A8%822%E7%89%88-USP%E7%A0%94%E7%A9%B6%E6%89%80/dp/4048930699/ref=pd_sim_14_4/356-0696996-4808706?_encoding=UTF8&pd_rd_i=4048930699&pd_rd_r=b8f5b6ef-42b8-46be-a705-56143336a7ae&pd_rd_w=ZbCUP&pd_rd_wg=OLwz8&pf_rd_p=4446cd16-eada-4bb1-91df-7c54a5fbd0b9&pf_rd_r=RX4TMKV8CAJC89GMME71&psc=1&refRID=RX4TMKV8CAJC89GMME71[フルスクラッチから1日でCMSを作る シェルスクリプト高速開発手法入門 改訂2版]

| 著者     | 上田隆一
| 出版日   | 2019/06/28
| ページ数 | 304
|====

ブログ用 CMS の自作をテーマにした本です。 markdown で書いた記事を GitHub に ``push`` すると、サーバが自動的に記事を更新する、という仕組みを整えます。

この本は、新たなシェルの入門書として作られたそうです。そして、 CMS の作成という『面白そうな』テーマが選ばれています。しかし、少なめの説明でどんどんシェルを使うため、この本が入門者向きであるとは思えません。

シェルの入門者が読みたいのは、『シェルプログラミング実用テクニック』の方ではないのかと思います。そして、そちらを読めば、この本を読む必要は無くなります。意図に反して、 *マニアックな本* になったのではないかと捉えます footnote:[マニアックな本は好きです] 。

2019 年に執筆された本だけあって、これ以上は無いと思うほど良い文で、シェルについて綴ってあります。 *プロの物書きの文章* といった印象で、買って良かったと思いました。

通信には、 https://en.wikipedia.org/wiki/Common_Gateway_Interface[CGI] という規格のおかげで、 stdin/stdout を使った普通のシェルスクリプトを使用できるようです。結局、 html の生成に最も力を使います。 CMS を作るのに必要な知識とは、 html/css の知識のようでした footnote:[下のレイヤに行かないで済む、というのが答えだとすると、少々肩透かしに思いました。] 。

=== 実践Vim

[cols="1,3"]
|====
| 書名     | https://tatsu-zine.com/books/practical-vim[実践Vin]

| 著者     | 新丈径（翻訳）、Drew Neil（著）
| 出版日   | 2013/8/29 (和書) 2015/11/08　(洋書 第二版)
| ページ数 | 400
|====

*砥石* のような本です。一周読むだけでVimの操作が改善されます。しかも、操作法は錆びることがない。おすすめです。

https://www.amazon.co.jp/Practical-Vim-Speed-Thought-English-ebook/dp/B018T6ZVPK[洋書]には第二版もあり、 https://pragprog.com/book/dnvim2/practical-vim-second-edition[Vim8 に対応している] そうです。

=== 独習Git

[cols="1,3"]
|====
| 書名     | https://www.amazon.co.jp/%E7%8B%AC%E7%BF%92Git-%E3%83%AA%E3%83%83%E3%82%AF%E3%83%BB%E3%82%A6%E3%83%9E%E3%83%AA/dp/4798144614/ref=tmm_other_meta_binding_swatch_0?_encoding=UTF8&qid=&sr=[独習Git]

| 著者     | リック・ウマリ (著), 吉川邦夫 (翻訳)
| 出版日   | 2016/2/26 (和書)
| ページ数 | 384
|====

ギター奏者のチュートリアルのように、『ゆっくりと演奏する』ことを心がけてGitを解説する、というような前書きの本でした。 *モチベーションに良かった* です。

_working directory_, _index_ などの基本的な概念を導入し、 _commit_ や _merge_ ができるようになります。本の構成上、 `.gitconfig` は付録のような位置にあるので、早めに読んで、コマンドを便利にすると良いと思います。

merge, _rebase_ については、合わせて https://www.slideshare.net/kotas/git-15276118[怖くないGit] というスライドを見ると、理解が深まりました。それ以上の細かいコマンドは、必要に応じて調べたら良いと思います。

NOTE: ちなみに、僕の `.gitconfig` の解説が https://toyboot4e.github.io/dotfiles/cli/git.html#gitconfig[ここ] にあります。  Git に慣れていない人こそ、こういうのが欲しいのではないかと思って書きました。

=== Pro Git (second edition)

[cols="1,3"]
|====
| 書名     | https://git-scm.com/book/en/v2[Pro Git]

| 著者     | Scott Chacon
| 出版日   | 2014/11/9 (洋書)
| ページ数 | 456
|====

公式の本です。あまり読んでいないのですが、タイトルに反して易しい本のようでした。肌に合うなら、この本で入門できそうです。

*web版、電子書籍版はフリー* です (https://git-scm.com/book/en/v2[サイト]) 。 3rd edition はしばらく出ないと思います。
