#+TITLE: AGC 065, ABC 334, 書く技術 / ガチ言語
#+DATE: <2023-12-24 Sun>

* AtCoder ガチ言語 Haskell 🔥

『[[https://zenn.dev/toyboot4e/books/seriously-haskell][AtCoder ガチ言語 Haskell 🔥]]』を投稿した。

Haskell で茶色コーダーを目指すための本があって欲しかった。もしも名著 [[https://booth.pm/ja/items/1577541][Haskellで戦う競技プログラミング]] に倍の分量があれば大方道のりが定まるはずで、ここを舗装しようというのは自分以外にいないと思った。

書いている間、不安しか無かった。文章を書くと知性が露呈してしまうもので、自分は支離滅裂な人間ですと公開してしまうことになる。しかし [[https://zenn.dev/toyboot4e/books/seriously-haskell/viewer/toc][目次の章]] を作ってからは、全体構成だけはそう間違っていないと確認できた。ちょっと安心した。

おそらく内容は失敗している。読みたいことが書いていなかったり、何を言っているのか分からないかもしれない。 100 % 僕の責任だ。本来、読み物はこんにゃくのように気持ちよく脳みそに収まってくれないといけない。

来年は強い理性を身に付けて、良い感じの文章に直したい。

* 競技プログラミング

** AGC 065

[[https://atcoder.jp/contests/agc065][AGC 065]] に参加した。 0 完だったにも関わらず、レーティングが上がってしまった。

[[https://atcoder.jp/contests/agc065/tasks/agc065_a][A 問題]] では QuickCheck を使って貪欲解が間違っていることを確認した。幅 10 のビームサーチを撃つ以外に成すすべが無かった。

** ABC 334

[[https://atcoder.jp/contests/abc334][ABC 334]] に参加した。疲れていて感想を書けない。

[[https://atcoder.jp/contests/abc334/tasks/abc334_c][C 問題]] は DP として解いた。

次回のコンテストは来年 1 月 6 日。

* 読書

[[https://bookclub.kodansha.co.jp/product?item=0000194754][論理が伝わる　世界標準の「書く技術」]] を 33 % まで読んだ。各段落の始めでメンタルモデルを示し、続く文章はメンタルモデルに沿って読める内容にせよということだった。読み手はオートマタみたいなものだと思った。

インテリが書く文章は 1 段落が長い傾向にあると思う。短期記憶領域の広さが現れたものと思っていたが、そもそも文章作りの意図が違ったのかもしれない。よし、こういう本を読んでいこうと思う。

