= ANF devlog #7: Roguelike
:cpp: pass:[C++]

== Devlog

お久しぶりです！　前回の ANF devlog から 2 ヶ月以上が経っていました。ついに今回、簡易ローグライクゲームを用意できたので、いろいろと書いていきます。

.前回までのあらすじ - Previously on ANF devlog
[sidebar]
--
ついにメディア (画像、音声、フォント) 関連のライブラリを取り揃えた ANF devlog 。『ゲーム制作』はもう目前だ！

しかしクラッシュが止まらない！　クラッシュが止まらない！！
--

=== The game

作ったゲームです:

動画

Youtube デビューしました？！　今後、ぼそぼそ喋る動画を挙げていくか検討中です。文字だけの方がいいかな。

== Notes

=== Algebra

ANF では代数ライブラリを自作しています。しかし、良いライブラリがすでに作られているので、そちらを使った方が良いと思います:

* https://docs.rs/glam/latest/glam/[glam]
+
Trait および generics が無く、 `f32` に特化しています。型名が短いのも良かったです (`Quat` が Quatertanion を表す、など) 。

* https://docs.rs/cgmath/latest/cgmath/[cgmath]
+
良さそうですね。

* https://docs.rs/nalgebra/latest/nalgebra/[nalgebra]
+
ちょっと抽象的すぎて難しそうです。

下に行くほど、ドキュメントの難度が上がって行きます。 {rokol} を使った 3D ゲームの方では、 glam を使ってみようと思います。

=== adbook, rokol

新たな SSG {adbook} を用意して、ブログ生成に使っています。 AsciiDoc で書ける mdBook モドキのつもりですが、クオリティには問題がありますね。

https://github.com/emacs-evil/evil[Evil] Emacs を使うための https://qiita.com/toyboot4e/items/71a1b40486e67c431197[67 のコミットを公開] しましたが、ほとんど相手にされませんでした。煽りタイトルが悪かったのでしょうか。悲しいなぁ。これからも独りよがりにやっていきます。

