#+TITLE: ドタバタ賃貸契約
#+DATE: <2025-09-10 Wed>
#+FILETAGS: :misc:

* 背景

近々東京勤務となるため、賃貸を契約しました。学生時代は激安賃貸に住んでいたり、現在までは社宅済みのため、まともに賃貸を探したのは初めてです。

以下では賃貸探しの経験を記載します。当たり前のことばかりかもしれませんが、備忘録として残しておきます。

* 賃貸契約について

** 前提条件

僕の前提条件は、庶民・男性・一人暮らしで、自動車・ペット無しです。一般的で探しやすい方だと思います。

#+BEGIN_QUOTE
ただし東京から離れた場所に住んでいるため、大いに旅費がかかります。この点は理解して行動した方が良かったです。
#+END_QUOTE

賃貸の必須条件は、大雑把に光回線とドラム式洗濯機にしました。条件は掘り下げが必要でしたので、詳細はおまけの項に記載します。

** 戦略

まずはネット (e.g. スマイティ) で候補物件を探した方が良いです。このような準備があると、候補地や賃料など基本的な部分を不動産に丸投げしなくて済むため、スムーズに話が進みます。

通常水曜日が不動産の定休日です。不動産は土日も営業しているため、金曜夜にオンラインミーティングして、土日に訪問する人が多そうです。

なお東京では (入居希望者の数 >> 賃貸の数) であるため、不動産との打ち合わせで内見まで進むケースは稀なようです (約 1 割？) 。そのため旅費を惜しむなら、不動産とはオンラインで打ち合わせし、目当ての物件が確定してから訪問・内見した方が良いです。

#+BEGIN_QUOTE
内見前や内見中に物件が埋まることもありますが、ラフプレーが可能な不動産だと何とかしてくれるかもしれません。
#+END_QUOTE

** 不動産とのコンタクトについて

僕の前提条件だと、 [[https://otayado.com/][おたくのやどかり]] が選ぶ物件は間違い無いと思います。この不動産は一定品質以上の物件を紹介してくれるため、良いベンチマークにもなります。ただし高品質の物件は 1 〜 2 日で無くなる上に、彼らは利用者を積極的にカバーするタイプではないため、一点張りだとリスクがあるかもしれません。

#+BEGIN_QUOTE
僕は馬鹿だったので、紹介して頂いた物件を逃し、旅費も 2 週間も無駄になりました。心 (情報) と体 (日程) の準備をし、紹介直後に契約できるようにしておくべきだったと思います。東京のスピード感を理解しておくべきでした。
#+END_QUOTE

仕方がないので、賃貸の紹介サイト (スマイティ) で物件を探し、サイトから不動産に一括でメールを送ってみました。 *即座に* 連絡が来るので、電話したり、 LINE 登録したりオンライン打ち合わせの日程を詰めました。

まあ上手く行きません。受身な不動産が相手だと、自分の無知に刺されます。危うく風俗街の賃貸を選んだり、エレベータの無い物件を選ぶところでした。また客に手間を押し付けるタイプの不動産だと、要望ガン無視で 30 件ぐらいのチラシを押し付けてくるので、ネットで物件を見ている方がマシだったりします。割とプレッシャーになりました。

** 名プレイヤーについて

不動産とのやり取りを続ける中、偶然名プレイヤーに出会いました。既に僕が一般の不動産に期待していなかった中、電話から Zoom 打ち合わせをねじ込んで、要望を聞き取り、本当に必須条件を満たす賃貸を探し、満足の行く別解を見つけてくれました。

いざ来店すると、ちょっとした質問を電話一本で解消し、スケジュール的に無理そうだった内見を勝ち取っており (連携プレー？) 、世間話や電話をしながら賃貸に向かい、レーザーポインタで超高速かつ精力的に計測を終え、書類関係をゴニョゴニョし、 RTA のように速攻で帰還……。

そこまでする？？　来店時に地元の土産物を持って行きましたが、全然対価に見合っていませんでした。もしかしたら仲介料は高いかもしれませんが (未確認) 、全然払える働きでした。本当に募集が蒸発しますからね……。

不動産は水曜日が定休日ですが、本当に週休 1 日で働いているそうです。水曜日にメッセージを返している時、『俺何してるんだろう……』と考えると零していたのが印象的でした。美味しいご飯屋を聞いたら、こちらの要望を聞いて (香辛料が強いお店) 、熟考の後、本人が行かないであろう中村屋を勧めてもらったのも面白い。適当に答えればいいのに、徹頭徹尾相手のための返事をしており、接客業なんだなと感じました。総評して、年収 1,200 万円ぐらい無いと割に合わない働きぶりだと思います。

この人が鬼のように働いてくれないとヤバかったです。ドラム式洗濯機についても詰めてくれましたし、スケジュール関係は僕よりよほど必死でした (隠していたので後で分かりました) 。あまり感銘を受けているようではダメなんですが、本当に凄くて刺激になりました……。

* おまけ

以下では話の邪魔になる詳細情報を記載します。

** 主な留意点について

スケジュールには要注意です。

- 賃貸は、契約後入居までに最低 2 週間かかると思います
- [[https://otayado.com/][おたくのやどかり]] では、初回打ち合わせまでに 2 週間弱はかかると思います (電話予約 → 打ち合わせ予約)

** 希望条件

*** 必須条件

以下はマストにしました。マストの条件以外は不動産には軽く伝える程度にしました。

- 勤務先までの交通機関の所要時間が 40 分以内
  - (Door to door ではない)
- 治安が良い
  全く気にしてなかったのですが、ある類の場所があまりにも評判が悪いため
  - 日本人の割合が高い
  - 風俗街ではない
- 賃料 + 管理費 < 87,000 円／月
  - 安い物件でも 77,000 円
  - 家賃は投資並みに影響がデカそう
- 高速な光回線が必須
  - 個人契約の光回線を引ける物件が第一候補
  - 基本的にインターネット無料の物件は禁止
  - 最大 10 GB の無料回線はギリギリ有りとする (仮)
    - =nixos-rebuild= したら死にそうではある
- エレベータ有り
  - 背の低い物件には設置義務が無いため要注意
  - 当たり前に思える条件ほどチェックを入れて検索すべき
    - たとえばエアコン設置済み
- Panasonic のドラム式洗濯機を設置可能
  - [[https://panasonic.jp/wash/check.html][洗濯機・洗濯乾燥機の設置について]]
    - 防水ピット 640x640, 高さは蛇口まで 1,350 くらいあれば余裕そう？
    - 左開き、右開きと設置箇所の関係も重要
      - 自然に開ける向きだと嬉しい
  - 搬入経路を内見時に測る必要有り
  - 結局 *洗濯機が一番の不安要素*

*** 優先条件

以下はオプショナルにしました。

- 専有面積 $22.00 \ m^2$ 以上
  - 帖 (畳) の単位はまちまちなため、専有面積で把握のこと
  - 専有面積が広くても、洋室部分が 6.5 帖以上無いと狭い
    - 洋室 6 畳なら他に優れた条件が欲しい
- ゴミ出し 24 時間制限無し
- 小さい宅配ボックス有り
- 大きい宅配ボックス有り
  - 例えばテーブルやモニタが入る
- 都市ガスのコンロが 2 口以上
- 調理スペースがある
- 自転車置き場がある

*** 夢の条件

以下は無理だと思って言いませんでした。

- お風呂の追い焚き有り

** 最終的に決まった物件

既に概ね特定できそうな情報を記載したので、これ以上の詳細は伏せます。

* 感想

ひとまず入居できそうでホッとしています。天井でディスコボールを回したり、ニトリの N ポルダを本棚にしたり、昇降デスクを買ったり、ベッドを搬入したり、好き放題やって行こうと思います。楽しみな設備もあったり。

不動産の名プレイヤーを見て、仕事って本来はこうなんだと思いました。ふにゃふにゃしてたりアグラをかくと、理想から離れていってマズイですね。差を感じましたし、この差を埋めようと本気で思っていない点が一番の違いなのかもしれません。もう少し何とかできるか……？

