#+TITLE: メキメキ新居環境構築
#+DATE: <2025-11-10 Mon>
#+FILETAGS: :misc:

* 背景

先日引っ越してから一新した物をメモします。

* 環境構築

** ベース

*** フロアタイル

[[https://asia-kobo.com/c/0000000101/0000000804/0000001029][アジア工房の置くだけフロアタイル]] を購入しました。複数社からサンプルを取り寄せましたが、ここの製品だけ表面をざらついた触感に仕上げてあって面白かったです。厚さ 3.5 mm のため、床面保護に十二分の信頼が置けます。雰囲気も出ました。

廊下に敷くと、玄関を開けた瞬間に『おっ』となれるのがちょっと良いかもしれません。

*** 照明

[[https://artworkstudio.co.jp/][ART WORK STUDIO]] の天井照明を購入しました。間接照明機能に惹かれましたが、見た目が好みではありません。簡易取り付け式のライティングレールにすれば良かったです。

*** 巾木 (はばぎ) を白く

配色のため、茶色い巾木はソフト巾木で覆うのが良さそうです。なぜ茶色にしたのでしょうか…… (コスト？) 。

** 家具

*** 昇降デスク

セールで Flexispot の [[https://www.flexispot.jp/e7h.html][E7H]] を購入しました。見た目の良い [[https://www.flexispot.jp/e7-pro.html][E7 Pro]] を買った方が良いです。巨大天板 (1.8m x 0.8m) を選びましたが、メープル色限定だったのが無念です
。

[[https://av.watch.impress.co.jp/docs/news/2011306.html][スピーカースタンド]] を取り付けて、 [[https://usa.yamaha.com/products/proaudio/speakers/hs_series/index.html][HS5]] をベストポジションに固定できたのが嬉しいです。幅広い天板のおかげで、日頃使うスペースが机の上に限定されました (部屋全体は荒れません) 。

*** 本棚

適当なラックを買って本棚にしました。棚板の耐荷重の問題で、全体の半分程度にしか本を置けません。高くて頑丈な製品を買ったほうが良かったです。

有り余った本は、デスク下のローデスクに平積みしています。もう少し雅にしたいです。

*** キャビネット (開き戸)

キーボード関係の備品を保管するキャビネットを購入しました。キャスター付きかつ開き戸で、しかも透明なのが気に入っています。体験良し！

*** ベッド

初めてベッドを購入しました ([[https://www.low-ya.com/goods/F909_G1015_1SD][Lowya 木目調ローベッド]]) 。今までは床で寝ていたため、冬場は冷気でスリップダメージを受けていましたが、ついに文明を手に入れました。

専有面積の広さが弱点ですが、空いていても物置と化すだけだったので、これで良いのかもしれません。

*** エアロバイク

[[https://www.alinco.co.jp/product/fitness/detail/id=5290][AFB7218]] が窓際に佇んでいます。この狭さでも意外と乗れます。今だと机付きの機種が良いかも。

** 金策

*** 調理器具

Youtube を参考に揃え直しました。特に Ballarini のフライパンが格好良くて、情報に感謝しています:

- [[https://www.youtube.com/watch?v=I8BL8HHhD70][主婦歴26年!キッチンアイテムマニア厳選のおすすめキッチン用品20選/vol.39]]

包丁も買っちゃいましたが、持ち手がダサくて残念でした。

*** 水筒

Atlas の 700 mL の水筒を購入しました。洗浄がそこそこ面倒です。透明な方が疑心暗鬼にならずに済むかも。

** 生活家電

*** 空気清浄機

洒落た空気清浄機を買ってみたのですが、フィルターが買い替え式で失敗しました。日本製を買った方が良かったです。

*** 掃除機

Dyson の掃除機を続投しています。置き方に困っており、ステーションタイプの方が良かったです。

*** 全自動コーヒーメーカー

[[https://www.delonghi.com/ja-jp/s/ECAM22112B][De'Longhi Magnifica S]] を購入し、会社に設置しました。意外とみんな使ってくれて嬉しいです。豆代の金策は検討中。

本来はエスプレッソマシンのようですが、日本版ではエスプレッソを薄めた『[[https://www.delonghi.com/ja-jp/faqs/%E3%80%90%E5%85%A8%E8%87%AA%E5%8B%95%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%E3%83%9E%E3%82%B7%E3%83%B3%E3%80%91%E3%80%8C%E3%82%AB%E3%83%95%E3%82%A7%E3%83%BB%E3%82%B8%E3%83%A3%E3%83%9D%E3%83%BC%E3%83%8D%E6%A9%9F%E8%83%BD%E3%80%8D%E3%81%A8%E3%81%AF%EF%BC%9F/a/250449][カフェ・ジャポーネ]]』なる抽出ができます。普通のコーヒーじゃん……とか思っていましたが、やや渋みが強い味になりました。少なくともインスタントコーヒーでは満足できなくなりました。

** その他

- iPhone 6s を iPhone SE 第３世代 (2022) に更新しました。充電の持ちが良くなりました。
- [[https://bitwarden.com/][Bitwarden]] (パスワードマネージャ) を導入しました。
- クレジットカードなど、諸々を整理しました。

* まとめ

フロアタイルを敷いて、デスクとベッド、収納などを置きました。見た目はかなり妥協していますが、やはりベッドを置いたことで文明度が上がったのが良かったと思います。

また購入品とは関係無いですが、お風呂に操作パネルが付いており、快適にお風呂に入れる点に満足しています。これは本当に引っ越して良かった！

