#+TITLE: ギターの基礎練を試してみました
#+DATE: <2026-05-31 Sun>
#+FILETAGS: :play:

* 背景

ギターの基礎練の方法をメモします。特に上達しようと思っておらず、ダラダラと気持ちよく続けられる方法を模索しています。下手です！

* 基礎練

** 準備

機材の準備をします。

- メトロノームとチューナーを買う
  無くした場合は改めて買い求めます。
- フットレスを買う
  ギターのボディを左足を載せて弾くと、疲れにくくなるそうです。買う価値ありです。
- コーティング弦を張る
  普通の弦はすぐに錆びてしまいます。コーティング弦を張ると弦の張替えが必要なタイミングが減り、練習時間が増えます。

** 自己修正

気持ち良く音が出るように自己修正します。

- 4/4 でメトロノームを鳴らす
  ヨレたリズムを少しでも修正します。
- 低いテンポで演奏する
  むしろ通常のスピードであまり練習しなくても良いかもしれません。
- 録音する
  修正すべき点に気付けない時は、積極的に見つける必要があります。面倒くさいので、やりたくありません。
- ブツ切りの音にしない
  明らかに音が悪いので修正します。
- ミュートにより反響音を減らす
  特にエレキギターの場合は反響音が衝突するため、ミュートが必要になります。
- 鏡を見る
  変な指の動かし方に気づきやすくなります。
- 目を瞑る
  これはこれで改善点を見つけやすくなって良いと思います。おすすめしている人を見たことがありませんが、気付きがほしい時には良いかも。
- 4/4 のメトロノームを裏拍で鳴らす
  鉄板の練習方法ですね。八分音符の練習だとやりやすいです。

** オルタネイト・ピッキング

ループするフレーズで練習します。逆向きも練習します。

- クロマチック・スケール (5678)
  16 分音符で 5678 を弾いたら弦移動します。
- ジグザグや斜めなクロマチック・スケール
  細かい弦移動を挟みます。
- スライドするクロマチック・スケール
  小節ごとに弦移動しつつ、始点を移動します。
- アルペジオのループ
  [[https://www.youtube.com/shorts/zcvxzcxv][CM7, Dm7 をループする]] やつなど。逆向きも練習します。

** さらなる上達方法

飽きてきたら新しいものを探します。

- 新しい演習方法を探す
- 今弾けない曲を練習する

* まとめ

現在の練習方法をメモしてみました。大して上手くなる日は来ないと思いますが、程々に、適度な経験値を積んでいきたいです。

