name: "Build"

on:
  push:
    branches: 'main'
  pull_request:

jobs:
  build:
    name: Build with Nix Flakes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    # TODO: cachix
    - name: Build the devlog
      run: |
        nix build .#devlog
    - name: Upload devlog artifact
      id: devlog-build
      uses: actions/upload-pages-artifact@v3
      with:
        path: result/out
