name: "Test"

# Stop other CI in the same branch on new run:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build devlog
      uses: ./.github/actions/build
