name: "Test"

# Stop other CI in the same branch on new run:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

# Deny all permissions by default; grant per job below
permissions: {}

# Run build only
jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    permissions:
      contents: read    # to check out the repository
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Build devlog
      uses: ./.github/actions/build
